module.exports = {
  testEnvironment: 'node',
  verbose: true,
  forceExit: true,
  detectOpenHandles: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  testTimeout: 10000, // Reduce timeout to 10 seconds
  setupFilesAfterEnv: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    '^@src/(.*)$': '<rootDir>/src/$1',
    '^@common/(.*)$': '<rootDir>/src/common/$1',
    '^@commonMiddlewares$': '<rootDir>/src/common/middlewares',
    '^@commonMiddlewares/(.*)$': '<rootDir>/src/common/middlewares/$1',
    '^@commonUtils$': '<rootDir>/src/common/utils',
    '^@commonUtils/(.*)$': '<rootDir>/src/common/utils/$1',
    '^@commonValidation$': '<rootDir>/src/common/validation',
    '^@commonValidation/(.*)$': '<rootDir>/src/common/validation/$1',
    '^@commonServices$': '<rootDir>/src/common/services',
    '^@commonServices/(.*)$': '<rootDir>/src/common/services/$1',
    '^@errors$': '<rootDir>/src/common/errors',
    '^@errors/(.*)$': '<rootDir>/src/common/errors/$1',
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@tests/(.*)$': '<rootDir>/tests/$1',
    '^@config$': '<rootDir>/src/config',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@app$': '<rootDir>/src/app.js',
  },
  testPathIgnorePatterns: ['/node_modules/', '/__tests__/helpers/'],
  coveragePathIgnorePatterns: ['/node_modules/', '/__tests__/helpers/'],
  testMatch: ['**/__tests__/**/*.test.js', '**/?(*.)+(spec|test).js'],
}
